### ISSUE TITLE
Roll back backtrace

### ISSUE THREAD

**Issue by taichi-ishitani** [ms-ati/docile#35]
Hi @ms-ati ,

I have an enhancement request about backtrace.

When a `NoMethodError` is raised inside the given block, the 1st entry of its back trace is not the original location.
For example,

```ruby
require 'docile'

foo = Object.new
bar = Object.new

Docile.dsl_eval(foo) do
  Docile.dsl_eval(bar) { fizz_buzz }
end
```

Execute above code then you can get following error message.

```
C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/fallback_context_proxy.rb:55:in `block in initialize': undefined method `fizz_buzz' for main:Object (NoMethodError)
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/fallback_context_proxy.rb:84:in `method_missing'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/fallback_context_proxy.rb:55:in `block in initialize'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/fallback_context_proxy.rb:84:in `method_missing'
        from docile_backtrace.rb:7:in `block (2 levels) in <main>'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `instance_exec'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `exec_in_proxy_context'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile.rb:43:in `dsl_eval'
        from docile_backtrace.rb:7:in `block in <main>'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `instance_exec'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `exec_in_proxy_context'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile.rb:43:in `dsl_eval'
```

The entry for the original location is this but the top entry is for `docile`'s code.

```
docile_backtrace.rb:7:in `block (2 levels) in <main>'
```

I'd like to roll back the backtrace to the original entry for perspicuity like below.

```
docile_backtrace.rb:7:in `block (2 levels) in <main>': undefined method `fizz_buzz' for main:Object (NoMethodError)
        from docile_backtrace.rb:7:in `block (2 levels) in <main>'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `instance_exec'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `exec_in_proxy_context'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile.rb:43:in `dsl_eval'
        from docile_backtrace.rb:7:in `block in <main>'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `instance_exec'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile/execution.rb:26:in `exec_in_proxy_context'
        from C:/Ruby/Ruby25-x64/lib/ruby/gems/2.5.0/gems/docile-1.3.1/lib/docile.rb:43:in `dsl_eval'
```

**Comment by ms-ati** [comment]
Very interesting @taichi-ishitani. Shall I look forward to seeing your work in this area?

**Comment by taichi-ishitani** [comment]
Yes, off course.
I will open a PR when I finish implementing this feature.

**Comment by ms-ati** [comment]
@taichi-ishitani Are you still working on this issue by any chance? Please let me know if I can be of assistance

**Comment by taichi-ishitani** [comment]
@ms-ati ,
Sorry for delay. I just open PR #36.

**Comment by ms-ati** [comment]
Thank you Taichi, I will try to review by end of day tomorrow (Monday).
-- 
Marc Siegel
Technology Specialist
American Technology Innovations

Email: marc@usainnov.com
Phone: 1 (617) 399-8145
Cell: 1 (617) 223-1220
Fax: 1 (617) 334-7975
