### ISSUE TITLE
Bug: Docile 1.3 breaks cfer 

### ISSUE THREAD

**Issue by ms-ati** [ms-ati/docile#38]
See how [this PR to bump Docile](https://github.com/seanedwards/cfer/pull/63) to 1.3.2 in the `cfer` project breaks its specs:

https://travis-ci.org/seanedwards/cfer/builds/601409476

```
RuntimeError:
  Expected a value or block when setting property DocileUndoFallback
# ./lib/cfer/block.rb:93:in `method_missing'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile/fallback_context_proxy.rb:87:in `method_missing'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile/execution.rb:29:in `exec_in_proxy_context'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile.rb:43:in `dsl_eval'
# ./lib/cfer/block.rb:12:in `build_from_block'
# ./lib/cferext/aws/iam/policy_generator.rb:15:in `statement'
# ./lib/cferext/aws/iam/policy_generator.rb:20:in `allow'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile/fallback_context_proxy.rb:87:in `method_missing'
# ./lib/cferext/aws/iam/policy_generator.rb:54:in `block in <module:IAM>'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile/execution.rb:26:in `instance_exec'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile/execution.rb:26:in `exec_in_proxy_context'
# /home/travis/.rvm/gems/ruby-2.5.5/gems/docile-1.3.2/lib/docile.rb:43:in `dsl_eval'
# ./lib/cfer/block.rb:12:in `build_from_block'
# ./lib/cferext/aws/iam/policy_generator.rb:48:in `generate_policy'
# ./lib/cferext/aws/iam/policy_generator.rb:53:in `<module:IAM>'
# ./lib/cferext/aws/iam/policy_generator.rb:5:in `<module:AWS>'
# ./lib/cferext/aws/iam/policy_generator.rb:4:in `<module:CferExt>'
# ./lib/cferext/aws/iam/policy_generator.rb:3:in `<top (required)>'
# ./lib/cferext/aws/iam/policy.rb:1:in `require'
# ./lib/cferext/aws/iam/policy.rb:1:in `<top (required)>'
# ./lib/cfer.rb:368:in `require'
# ./lib/cfer.rb:368:in `block in <top (required)>'
# ./lib/cfer.rb:368:in `each'
# ./lib/cfer.rb:368:in `<top (required)>'
# ./spec/spec_helper.rb:64:in `require'
# ./spec/spec_helper.rb:64:in `<top (required)>'
# ./spec/cfer_spec.rb:1:in `require'
# ./spec/cfer_spec.rb:1:in `<top (required)>'
```

**Comment by ms-ati** [comment]
This same issues is represented in the cfer project here:
https://github.com/seanedwards/cfer/issues/50

**Comment by seanedwards** [comment]
This was a bug in cfer and has been fixed on my side.
